### ISSUE TITLE
Remove duplicate type definitions after switching to grpc client

### ISSUE THREAD

**Issue by feiskyer** [hyperhq/hypernetes#136]
Types in `pkg/kubelet/hyper/types.go` are duplicated with grpc client's type, they should be replaced with grpc client's type.

This should be done togather while refactoring hyper client.

**Comment by resouer** [comment]
cc @YaoZengzeng ping me whenever you finished refactoring your existing PRs, I will begin to continue review. :+1:

**Comment by YaoZengzeng** [comment]
get it!

**Comment by resouer** [comment]
All done!
