### ISSUE TITLE
Use stdcopy for non-tty exec and attach

### ISSUE THREAD

**Issue by feiskyer** [hyperhq/hypernetes#147]
PR https://github.com/hyperhq/hyperd/pull/426 changed hyperd behavior of non-tty exec and attach.

**Comment by resouer** [comment]
NOTE: did not see any influence from 426 for now.

**Comment by feiskyer** [comment]
Have you tried starting container with and without tty?

**Comment by resouer** [comment]
Close this due to both tty & non-tty mode works as expected
