### ISSUE TITLE
Centos Keeps getting updated to 7.3

### ISSUE THREAD

**Issue by infinitydon** [hyperhq/hypernetes#159]
Hi,

I tired installing hypernetes today but got into a rabbitmq error (there is workaround for mitaka for this by adjusting the /etc/hosts file to reflect the hostname mapping to the ip address).

Then i tried running the install script, then I got the error that it only supports centos 7.2 (which is the version i started with).

So it seems during the installation, centos gets upgraded to 7.3...

[root@hypernetes kubernetes]# hack/local-up-hypernetes.sh
Start kube::util::verify_system
Only CentOS 7.2 is supported.
Run 'yum -y update' upgrade the system.
[root@hypernetes kubernetes]# 

[root@hypernetes kubernetes]# cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 

Is there a way to force centos from upgrading itself?

N.B -- I did not add any repos myself (including epel).

**Comment by resouer** [comment]
@infinitydon  It should works on CentOS 7.*, I will send a quick patch to update the scripts.
