### ISSUE TITLE
where's the code of hyper-apiserver?

### ISSUE THREAD

**Issue by keontang** [hyperhq/hypernetes#167]
RT

**Comment by gnawux** [comment]
If you are asking for the api server of hyper.sh, the api server is not open-sourced.

**Comment by gnawux** [comment]
@keontang if you ask for the api-server for the open sourced hypernetes project. 

Currently our main effort is to move the hypernetes as vanilla kubernetes + plugins, and there is no ongoing working on the stand-alone api-server yet. However, it is appreciated if you'd like working on it.

**Comment by keontang** [comment]
I want to know how hyper-apiserver and keystone work together just as described on the picture in README.md

**Comment by feiskyer** [comment]
@keontang  The original plan is: hyper-apiserver invoke keystone for auth, and then follows standard kubernetes API.

Sorry for the confusing. I'm removing the component from the architecture.
