### ISSUE TITLE
sed: cannot rename /etc/sedqp9KU2: Device or resource busy

### ISSUE THREAD

**Issue by yu8833** [hyperhq/hypernetes#170]
When I run hack/local-up-hypernetes.sh, on [docker playground](http://labs.play-with-docker.com/) with centos 7.2.1511 & 7.3.1611, the error message is 
***[root@50f7621a761a kubernetes]# hack/local-up-hypernetes.sh
Start kube::util::verify_system
Start kube::util::setup_hostname
sed: cannot rename /etc/sedqp9KU2: Device or resource busy***

How to solve it?
Thanks!

**Comment by feiskyer** [comment]
@YuPengZTE There are some problems of running kubernetes components inside docker containers, e.g. kubelet requires many privileges. Could you have a try on centos VM or bare metal host?

**Comment by yu8833** [comment]
Thanks @feiskyer .
I run with command:
***$ docker run --privileged --rm -ti centos:7.2.1511***
The error is still on .

Inside docker containers, there are many problems, I will try on centos VM, thank you!

**Comment by nelsonfassis** [comment]
How did you fix it @YuPengZTE ?
I'm having the same issue trying to build a cassandra_exporter, using --privileged didn't work
