### ISSUE TITLE
Could hypernetes be used without the neutron?

### ISSUE THREAD

**Issue by wangzhezhe** [hyperhq/hypernetes#61]
Hi !
Our case is following：
We are quite familiar with the deployment of k8s, and we just want to deploy the hypernetes which use hyper instead of docker deamon in k8s without using the neutron and keystone. Is hypernetes binding with the components of openstack tightly ? What should we do if we do not want to use extra function in networking and multi tenants? 
Thank you !

**Comment by feiskyer** [comment]
Of course, you can use hypernetes with same config with kubernetes except set kubelet container runtime to hyper:

``` sh
kubelet --... --container-runtime=hyper
```
