### ISSUE TITLE
Is this a new version that integrate Kubernetes with Hyper?

### ISSUE THREAD

**Issue by n0ndual** [hyperhq/hypernetes#7]
I thought it would be very promising to integrate kubernetes with hyper, and I found this project. But there is no documents in Hyper.sh and in this project. So will you please add some information about your plan

**Comment by gnawux** [comment]
@scorpionis yes, we are preparing the documents and will show the first demo in the coming OpenStack summit in tokyo in this month.

**Comment by feiskyer** [comment]
@scorpionis Thanks for interest, doc is at https://github.com/hyperhq/hypernetes-book

**Comment by n0ndual** [comment]
thank you gues for your reply, im gonna try this
